site_name: caijiqhx notes
site_author: caijiqhx
site_url: https://notes.caijiqhx.top

# Repository
repo_name: caijiqhx/Notes
repo_url: https://github.com/caijiqhx/Notes
copyright: "Copyright &copy; 2020 caijiqhx"

# Contents
nav:
  - Introduction:
      - index.md
      - TOP.md
  - 常用工具:
      - tools/vscode.md
      - tools/manjaro.md
      - tools/gitbook.md
      - tools/regex.md
      - mkdocs: tools/mkdocs.md
      - tools/mkdocs_zh_search.md
      - vim: tools/vim.md
      - 部署工具:
          - Docker 简介: tools/docker/docker_introduction.md
          - Dockerfile: tools/docker/dockerfile.md
      - 调试工具:
          - IDA: tools/ida.md
  - Rust:
      - rust/index.md
      - Rust 程序设计语言:
          - rust/trpl/index.md
          - rust/trpl/0x00.md
          - rust/trpl/0x01.md
          - rust/trpl/0x02.md
          - rust/trpl/0x03.md
  - C++:
      - cpp/index.md
      - cpp/memo.md
      - cpp/casting.md
      - cpp/rtti.md
      - cpp/unordered_set.md
      - cpp/custom_compare.md
      - C++ 11/14 快速上手:
          - 简介: cpp/c++_11_14/0.md
          - 语言可用性的强化: cpp/c++_11_14/1.md
          - 语言运行期的强化: cpp/c++_11_14/2.md
          - 对标准库的扩充：新增容器: cpp/c++_11_14/3.md
          - 对标准库的扩充：智能指针和引用计数: cpp/c++_11_14/4.md
          - 对标准库的扩充：正则表达式: cpp/c++_11_14/5.md
          - 对标准库的扩充：语言级线程支持: cpp/c++_11_14/6.md
          - 其他杂项: cpp/c++_11_14/7.md
          - C++17 简介: cpp/c++_11_14/8.md
      - STL 学习: cpp/stl_learning.md
      - 设计模式:
          - cpp/design_pattern/index.md
          - cpp/design_pattern/basic.md
          - 创建型模式:
              - cpp/design_pattern/simple_factory.md
              - cpp/design_pattern/factory_method.md
              - cpp/design_pattern/abstract_factory.md
              - cpp/design_pattern/builder.md
  - 计算机网络:
      - network/index.md
      - network/questions.md
      - network/tcp_and_udp.md
      - network/protocols.md
      - network/ip_addr.md
      - network/devices.md
      - network/http.md
      - network/http_status_code.md
  - 操作系统:
      - os/index.md
      - os_lab:
          - os/os_lab/index.md
          - lab1:
              - os/os_lab/lab1/exer1.md
              - os/os_lab/lab1/exer2.md
              - os/os_lab/lab1/exer3.md
              - os/os_lab/lab1/exer4.md
              - os/os_lab/lab1/exer5.md
              - os/os_lab/lab1/exer6.md
              - os/os_lab/lab1/challenge.md
              - os/os_lab/lab1/lab1.md
          - lab2:
              - os/os_lab/lab2/preview.md
              - os/os_lab/lab2/exer1.md
              - os/os_lab/lab2/exer2.md
              - os/os_lab/lab2/exer3.md
              - os/os_lab/lab2/challenge.md
              - os/os_lab/lab2/lab2.md
          - lab3:
              - os/os_lab/lab3/preview.md
              - os/os_lab/lab3/exer1.md
              - os/os_lab/lab3/exer2.md
              - os/os_lab/lab3/challenge.md
              - os/os_lab/lab3/lab3.md
          - lab4:
              - os/os_lab/lab4/preview.md
              - os/os_lab/lab4/exer1.md
              - os/os_lab/lab4/exer2.md
              - os/os_lab/lab4/exer3.md
              - os/os_lab/lab4/lab4.md
          - lab5:
              - os/os_lab/lab5/preview.md
              - os/os_lab/lab5/exer1.md
              - os/os_lab/lab5/exer2.md
              - os/os_lab/lab5/exer3.md
              - os/os_lab/lab5/lab5.md
          - lab6:
              - os/os_lab/lab6/preview.md
              - os/os_lab/lab6/exer1.md
              - os/os_lab/lab6/exer2.md
              - os/os_lab/lab6/lab6.md
          - lab7:
              - os/os_lab/lab7/preview.md
              - os/os_lab/lab7/exer1.md
              - os/os_lab/lab7/exer2.md
              - os/os_lab/lab7/lab7.md
          - lab8:
              - os/os_lab/lab8/preview.md
              - os/os_lab/lab8/exer1.md
              - os/os_lab/lab8/exer2.md
              - os/os_lab/lab8/lab8.md
  - 数据库:
      - database/index.md
      - database/theory.md
      - database/sql.md
      - database/mysql.md
      - database/sqlite.md
  - UCAS:
      - ucas/index.md
      - 虚拟化概述: ucas/virtualization_overview/virtualization.md
      - 侧信道攻击: 
          - ucas/side_channel/side_channel.md
          - ucas/zombieload/zombieload.md
          - ucas/zombieload/zombieload_script.md
      - Spectre: ucas/spectre/spectre.md
      - QEMU/KVM:
          - ucas/qemu_kvm/index.md
          - ucas/qemu_kvm/qemu_kvm_overview.md
      - Linux Kernel:
          - ucas/the_art_of_linux_kernel_design/index.md
          - ucas/the_art_of_linux_kernel_design/boot_to_main.md
          - ucas/the_art_of_linux_kernel_design/initial_and_create_process_0.md
          - ucas/the_art_of_linux_kernel_design/create_process_1_and_execute.md

# Customization
extra_javascript:
  - "static/js/extra.js"
  - "https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"

extra_css:
  - "static/css/extra.css"

# theme
theme:
  name: "material"
  language: "zh"
  palette:
    primary: "teal"
    accent: "red"
  icon:
    logo: material/cloud
  features:
    - tabs
    - instant
  feature:
    tabs: true
  font:
    text: "Noto Sans"
    code: "Source Code Pro"

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: "*"
  - codehilite:
      linenums: true
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true
      separator: '[\s\-\.]+'
      lang:
        - en
        # - ja
  - git-revision-date-localized
