site_name: caijiqhx notes
site_author: caijiqhx
site_url: https://caijiqhx-notes.readthedocs.io

# Repository
repo_name: caijiqhx/Notes
repo_url: https://github.com/caijiqhx/Notes

copyright: "Copyright &copy; 2020 caijiqhx"

# Contents
nav:
  - Introduction:
      - index.md
  - 常用工具:
      - 文档工具: tools/mkdocs.md
      - 部署工具:
          - Docker 简介: tools/docker/docker_introduction.md
          - Dockerfile: tools/docker/dockerfile.md
      - 调试工具:
          - IDA: tools/ida.md
  - 安全技术:
      - 栈介绍: sec_tech/stackoverflow/stack_introduction.md
  - 逆向分析:
      - reverse/index.md

  - C++:
      - C++ 11/14 快速上手:
          - 简介: cpp/c++_11_14/0.md
          - 语言可用性的强化: cpp/c++_11_14/1.md
          - 语言运行期的强化: cpp/c++_11_14/2.md
          - 对标准库的扩充：新增容器: cpp/c++_11_14/3.md
          - 对标准库的扩充：智能指针和引用计数: cpp/c++_11_14/4.md
          - 对标准库的扩充：正则表达式: cpp/c++_11_14/5.md
          - 对标准库的扩充：语言级线程支持: cpp/c++_11_14/6.md
          - 其他杂项: cpp/c++_11_14/7.md
          - C++17 简介: cpp/c++_11_14/8.md
      - STL 学习: cpp/stl_learning.md

# Customization
extra_javascript:
  - "static/js/extra.js"
  - "https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"

# theme
theme:
  name: "material"
  language: "zh"
  palette:
    primary: teal
    accent: red
  feature:
    tabs: true
  font:
    text: "Noto Sans"
    code: "Source Code Pro"

markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - pymdownx.arithmatex
